version: "3.8"

services:
  api:
    build: .
    volumes:
      - "./:/app"
      - "/app/node_modules"
    ports:
      - "5050:5050"
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: covidManagementDB
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./docker/data/db:/var/lib/mysql
